import 'dart:convert';
import 'dart:io';

import 'report_generator.dart';
import 'sweep_result.dart';

/// Posts or updates LocaleSweep results as a GitHub PR comment.
class GitHubReporter {
  /// GitHub API token.
  final String token;

  /// Repository in `owner/repo` format.
  final String repo;

  /// PR number to comment on.
  final int prNumber;

  const GitHubReporter({
    required this.token,
    required this.repo,
    required this.prNumber,
  });

  /// Creates a reporter from `GITHUB_TOKEN`, `GITHUB_REPOSITORY`, and `GITHUB_REF`.
  factory GitHubReporter.fromEnv() {
    final token = Platform.environment['GITHUB_TOKEN'];
    final repo = Platform.environment['GITHUB_REPOSITORY'];
    final prRef = Platform.environment['GITHUB_REF'];

    if (token == null || repo == null || prRef == null) {
      throw StateError(
        'Missing GitHub environment variables. '
        'Required: GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_REF',
      );
    }

    final prMatch = RegExp(r'refs/pull/(\d+)/merge').firstMatch(prRef);
    if (prMatch == null) {
      throw StateError('GITHUB_REF does not reference a PR: $prRef');
    }

    return GitHubReporter(
      token: token,
      repo: repo,
      prNumber: int.parse(prMatch.group(1)!),
    );
  }

  /// Posts or updates a PR comment with the sweep results.
  Future<void> postComment(SweepRunSummary summary) async {
    final markdown = ReportGenerator.generateMarkdown(
      summary,
      screenshotLinkBuilder: (path) => '`${path.split('/').last}`',
    );
    final commentBody =
        '<!-- locale_sweep -->\n$markdown\n---\n*Generated by [LocaleSweep](https://pub.dev/packages/locale_sweep)*';

    final existingCommentId = await _findExistingComment();

    if (existingCommentId != null) {
      await _updateComment(existingCommentId, commentBody);
    } else {
      await _createComment(commentBody);
    }
  }

  Future<int?> _findExistingComment() async {
    final response = await _request(
      'GET',
      '/repos/$repo/issues/$prNumber/comments',
    );

    if (response.statusCode != 200) return null;

    final comments = jsonDecode(response.body) as List;
    for (final comment in comments) {
      final body = comment['body'] as String? ?? '';
      if (body.contains('<!-- locale_sweep -->')) {
        return comment['id'] as int;
      }
    }
    return null;
  }

  Future<void> _createComment(String body) async {
    final response = await _request(
      'POST',
      '/repos/$repo/issues/$prNumber/comments',
      body: {'body': body},
    );

    if (response.statusCode != 201) {
      throw StateError(
        'Failed to create PR comment: ${response.statusCode} ${response.body}',
      );
    }
  }

  Future<void> _updateComment(int commentId, String body) async {
    final response = await _request(
      'PATCH',
      '/repos/$repo/issues/comments/$commentId',
      body: {'body': body},
    );

    if (response.statusCode != 200) {
      throw StateError(
        'Failed to update PR comment: ${response.statusCode} ${response.body}',
      );
    }
  }

  Future<_SimpleResponse> _request(
    String method,
    String path, {
    Map<String, dynamic>? body,
  }) async {
    final client = HttpClient();
    try {
      final uri = Uri.parse('https://api.github.com$path');
      final request = await (switch (method) {
        'GET' => client.getUrl(uri),
        'POST' => client.postUrl(uri),
        'PATCH' => client.patchUrl(uri),
        _ => client.openUrl(method, uri),
      });

      request.headers.set('Authorization', 'Bearer $token');
      request.headers.set('Accept', 'application/vnd.github.v3+json');
      request.headers.set('Content-Type', 'application/json');

      if (body != null) {
        request.write(jsonEncode(body));
      }

      final response = await request.close();
      final responseBody = await response.transform(utf8.decoder).join();
      return _SimpleResponse(response.statusCode, responseBody);
    } finally {
      client.close();
    }
  }
}

class _SimpleResponse {
  final int statusCode;
  final String body;
  _SimpleResponse(this.statusCode, this.body);
}
