import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;

import 'report_generator.dart';
import 'sweep_result.dart';

/// Posts or updates LocaleSweep results as a GitHub PR comment.
class GitHubReporter {
  /// GitHub API token.
  final String token;

  /// Repository in `owner/repo` format.
  final String repo;

  /// PR number to comment on.
  final int prNumber;

  const GitHubReporter({
    required this.token,
    required this.repo,
    required this.prNumber,
  });

  /// Creates a reporter from `GITHUB_TOKEN`, `GITHUB_REPOSITORY`, and `GITHUB_REF`.
  factory GitHubReporter.fromEnv() {
    final token = Platform.environment['GITHUB_TOKEN'];
    final repo = Platform.environment['GITHUB_REPOSITORY'];
    final prRef = Platform.environment['GITHUB_REF'];

    if (token == null || repo == null || prRef == null) {
      throw StateError(
        'Missing GitHub environment variables. '
        'Required: GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_REF',
      );
    }

    final prMatch = RegExp(r'refs/pull/(\d+)/merge').firstMatch(prRef);
    if (prMatch == null) {
      throw StateError('GITHUB_REF does not reference a PR: $prRef');
    }

    return GitHubReporter(
      token: token,
      repo: repo,
      prNumber: int.parse(prMatch.group(1)!),
    );
  }

  /// Posts or updates a PR comment with the sweep results.
  Future<void> postComment(SweepRunSummary summary) async {
    final markdown = ReportGenerator.generateMarkdown(summary);
    final commentBody =
        '<!-- locale_sweep -->\n$markdown\n---\n*Generated by [LocaleSweep](https://github.com/AstrixelHQ/locale_sweep)*';

    final existingCommentId = await _findExistingComment();

    if (existingCommentId != null) {
      await _updateComment(existingCommentId, commentBody);
    } else {
      await _createComment(commentBody);
    }
  }

  Future<int?> _findExistingComment() async {
    final uri = Uri.parse(
      'https://api.github.com/repos/$repo/issues/$prNumber/comments',
    );
    final response = await http.get(uri, headers: _headers);

    if (response.statusCode != 200) return null;

    final comments = jsonDecode(response.body) as List;
    for (final comment in comments) {
      final body = comment['body'] as String? ?? '';
      if (body.contains('<!-- locale_sweep -->')) {
        return comment['id'] as int;
      }
    }
    return null;
  }

  Future<void> _createComment(String body) async {
    final uri = Uri.parse(
      'https://api.github.com/repos/$repo/issues/$prNumber/comments',
    );
    final response = await http.post(
      uri,
      headers: _headers,
      body: jsonEncode({'body': body}),
    );

    if (response.statusCode != 201) {
      throw StateError(
        'Failed to create PR comment: ${response.statusCode} ${response.body}',
      );
    }
  }

  Future<void> _updateComment(int commentId, String body) async {
    final uri = Uri.parse(
      'https://api.github.com/repos/$repo/issues/comments/$commentId',
    );
    final response = await http.patch(
      uri,
      headers: _headers,
      body: jsonEncode({'body': body}),
    );

    if (response.statusCode != 200) {
      throw StateError(
        'Failed to update PR comment: ${response.statusCode} ${response.body}',
      );
    }
  }

  Map<String, String> get _headers => {
    'Authorization': 'Bearer $token',
    'Accept': 'application/vnd.github.v3+json',
    'Content-Type': 'application/json',
  };
}
